import assetsJSON from '../../webpack-assets.json';
import favicon from '../assets/images/favicon.ico';
import touchicon from '../assets/images/icon.png';

function renderFullPage(content, reduxState, head, currentEntry) {
  return `
    <!doctype html>
    <html>
      <head>
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        ${head.title.toString()}
        ${head.meta.toString()}

        <link rel="icon" type="image/x-icon" href=${favicon} />
        <link rel="apple-touch-icon" href=${touchicon} />

        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" />
        <link href=${assetsJSON[currentEntry].css} rel="stylesheet" />

        <script type="text/javascript" charSet="utf-8">
          window.__REDUX_STATE__ = ${reduxState}
        </script>
      </head>
      <body>
        <div id="app-mount-point">${content}</div>
        <!-- entry script generated by webpack -->
        <script src=${assetsJSON[currentEntry].js} type="text/javascript" charSet="utf-8"></script>
      </body>
    </html>
  `;
}

export default renderFullPage;
