import React from 'react';
import { Component } from 'react';
import PropTypes from 'prop-types';

const assetsJSON = require('../../webpack-assets.json');

import favicon from '../assets/images/favicon.ico';
import touchicon from '../assets/images/icon.png';

export default class Layout extends Component {
  static propTypes = {
    content: PropTypes.object,
    reduxState: PropTypes.string,
    head: PropTypes.object
  }

  render() {
    const { content, reduxState, head } = this.props;
    return (
      <html>
        <head>
          <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
          {head.title.toComponent()}
          {head.meta.toComponent()}

          <link rel="icon" type="image/x-icon" href={favicon} />
          <link rel="apple-touch-icon" href={touchicon} />

          <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" />
          <link href={assetsJSON.main.css} rel="stylesheet" />

          <script type="text/javascript" charSet="utf-8" dangerouslySetInnerHTML={{__html: `
            window.__REDUX_STATE__ = ${reduxState}
          `}} />
        </head>
        <body>
          <div id="app-mount-point">
            {content}
          </div>
          {/* entry script generated by webpack*/}
          <script src={assetsJSON.main.js} type="text/javascript" charSet="utf-8"></script>
        </body>
      </html>
    );
  }
}
