env:
  node: true
  browser: true
extends: 
  - 'airbnb'
parser: 'babel-eslint'
rules:
  react/jsx-filename-extension:
    - error
    - extensions: 
      - '.js'
      - '.jsx'

  # TODO: can be removed after airbnb publish there new version
  jsx-a11y/anchor-is-valid:
    - error
    - components: 
        - 'Link'
      specialLink: 
        - 'to'
