env:
  node: true
  browser: true
extends: 
  - 'airbnb'
parser: 'babel-eslint'
rules:
  react/jsx-filename-extension:
    - error
    - extensions: 
      - '.js'
      - '.jsx'

  # eslint-airbnb enable this by default disabled rule
  # turn this off here for convenience
  # remove this setting if you want strict proptype documentation
  react/forbid-prop-types:
    - off

  # TODO: can be removed after airbnb publish there new version
  jsx-a11y/anchor-is-valid:
    - error
    - components: 
        - 'Link'
      specialLink: 
        - 'to'
